Feature/payments
DEFRA/epr-payment-facade pull request #2
Opened 2024-07-09 12:37 UTC by paulshimmen

This branch does the majority of the GovPay initiate payment code. Health check is working. Unit and integration tests are working. Payment is being inserted and updated into the database via the service project. A test index.html page has also been created which will test the re-direct to GovPay. The method to redirect is not ideal. I changed it for testing purposes, and also because I was getting CORs issues with swagger when testing.

2024-07-12 14:29 UTC, manishagarwalEviden requested changes

2024-07-12 15:06 UTC, paulshimmen commented on src/EPR.Payment.Facade/Controllers/Payments/PaymentsController.cs
> +        <!DOCTYPE html>
Ok, will create a private method as suggested.

2024-07-12 15:08 UTC, paulshimmen commented on src/EPR.Payment.Facade.Common/RESTServices/Payments/HttpGovPayService.cs
> +            var url = "payments";
I will create a static constants class for the specific parts of the endpoint.

2024-07-12 15:08 UTC, paulshimmen commented on src/EPR.Payment.Facade.Common/RESTServices/Payments/HttpPaymentsService.cs
> +            var url = "payments";
I will create a static constants class for the specific parts of the endpoint.

2024-07-12 15:08 UTC, paulshimmen commented on src/EPR.Payment.Facade.Common/RESTServices/Payments/HttpPaymentsService.cs
> +            var url = $"payments/{id}";
I will create a static constants class for the specific parts of the endpoint.

2024-07-16 08:13 UTC, paulshimmen commented on src/EPR.Payment.Facade.Common.UnitTests/RestServices/HttpGovPayServiceTests.cs
> +        public async Task InitiatePayment_Success_ReturnsPaymentResponseDto()
I have added automoqdata for all tests where appropriate

2024-07-16 08:14 UTC, paulshimmen commented on src/EPR.Payment.Facade.Common.UnitTests/RestServices/HttpGovPayServiceTests.cs
> +            result.Should().NotBeNull();
I have reviewed all tests and added assertionscope  where appropriate.

2024-07-16 08:14 UTC, paulshimmen commented on src/EPR.Payment.Facade.Common.UnitTests/RestServices/HttpGovPayServiceTests.cs
> +            {
Have added automoqdata here

2024-07-16 08:14 UTC, paulshimmen commented on src/EPR.Payment.Facade.Common/Dtos/Request/Payments/GovPayPaymentRequestDto.cs
> +﻿using EPR.Payment.Facade.Common.Validators;
Renamed to GovPayRequestDto

2024-07-16 08:14 UTC, paulshimmen commented on src/EPR.Payment.Facade.Common.UnitTests/RestServices/HttpGovPayServiceTests.cs
> +                Amount = 14500,
Done

2024-07-16 08:15 UTC, paulshimmen commented on src/EPR.Payment.Facade/Controllers/Payments/PaymentsController.cs
> +    public async Task<IActionResult> InitiatePayment([FromBody] PaymentRequestDto request, CancellationToken cancellationToken)
As discussed will leave this as dto object as it is actually a data transfer object.

2024-07-17 10:01 UTC, manishagarwalEviden approved these changes

2024-07-17 10:01 UTC, merged